## Challenge 2: Sets

There are a lot to learn about Python Sets and the information presented in the lesson is limited due to its length. To learn Python Sets in depth you are strongly encouraged to review the W3Schools tutorial on [Python Sets Examples and Methods](https://www.w3schools.com/python/python_sets.asp) before you work on this lab. Some difficult questions in this lab have their solutions in the W3Schools tutorial.

#### First, import the Python `random` library.

In [2]:
import random

#### In the cell below, create a list named `sample_list_1` with 80 random values.

Requirements:

* Each value is an integer falling between 0 and 100.
* Each value in the list is unique.

Print `sample_list_1` to review its values

*Hint: use `random.sample` ([reference](https://docs.python.org/3/library/random.html#random.sample)).*

In [3]:
sample_list_1 = random.sample(range(0, 101), 80)
print(sample_list_1)

[74, 13, 59, 69, 44, 93, 76, 77, 62, 53, 16, 19, 92, 81, 33, 83, 24, 90, 65, 40, 85, 26, 0, 100, 31, 37, 32, 35, 61, 71, 96, 14, 43, 20, 84, 63, 2, 56, 27, 86, 41, 18, 78, 49, 46, 17, 1, 88, 21, 55, 79, 28, 9, 54, 57, 73, 11, 75, 82, 34, 67, 66, 50, 87, 29, 25, 97, 22, 10, 36, 80, 12, 23, 4, 8, 15, 45, 30, 68, 51]

#### Convert `sample_list_1` to a set called `set1`. Print the length of the set. Is its length still 80?

In [4]:
set1 = set(sample_list_1)
print("set1:", set1)
print("Length of set1:", len(set1))

set1: {0, 1, 2, 4, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 40, 41, 43, 44, 45, 46, 49, 50, 51, 53, 54, 55, 56, 57, 59, 61, 62, 63, 65, 66, 67, 68, 69, 71, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 90, 92, 93, 96, 97, 100}
Length of set1: 80

#### Create another list named `sample_list_2` with 80 random values.

Requirements:

* Each value is an integer falling between 0 and 100.
* The values in the list don't have to be unique.

*Hint: Use a FOR loop.*

In [5]:
sample_list_2 = []

for _ in range(80):
    sample_list_2.append(random.randint(0, 100))  # allows duplicates

print("sample_list_2:", sample_list_2)

sample_list_2: [75, 53, 87, 85, 85, 92, 16, 18, 65, 37, 83, 35, 96, 5, 81, 72, 2, 28, 10, 40, 98, 11, 35, 20, 15, 17, 96, 61, 91, 9, 0, 39, 28, 9, 49, 10, 71, 4, 10, 14, 77, 35, 69, 89, 83, 78, 58, 63, 42, 66, 3, 86, 3, 53, 62, 62, 68, 35, 56, 3, 54, 35, 89, 68, 13, 48, 94, 51, 50, 9, 56, 28, 2, 99, 11, 55, 71, 8, 25, 54]

#### Convert `sample_list_2` to a set called `set2`. Print the length of the set. Is its length still 80?

In [6]:
set2 = set(sample_list_2)
print("set2:", set2)
print("Length of set2:", len(set2))

set2: {0, 2, 3, 4, 5, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 20, 25, 28, 35, 37, 39, 40, 42, 48, 49, 50, 51, 53, 54, 55, 56, 58, 61, 62, 63, 65, 66, 68, 69, 71, 72, 75, 77, 78, 81, 83, 85, 86, 87, 89, 91, 92, 94, 96, 98, 99}
Length of set2: 56

#### Identify the elements present in `set1` but not in `set2`. Assign the elements to a new set named `set3`.

In [7]:
set3 = set1 - set2
print("set3:", set3)

set3: {1, 12, 19, 21, 22, 23, 24, 26, 27, 29, 30, 31, 32, 33, 34, 36, 41, 43, 44, 45, 46, 57, 59, 67, 73, 74, 76, 79, 80, 82, 84, 88, 90, 93, 97, 100}

#### Identify the elements present in `set2` but not in `set1`. Assign the elements to a new set named `set4`.

In [8]:
set4 = set2 - set1
print("set4:", set4)

set4: {98, 3, 99, 5, 39, 72, 42, 48, 89, 58, 91, 94}

#### Now Identify the elements shared between `set1` and `set2`. Assign the elements to a new set named `set5`.

In [9]:
set5 = set1 & set2
print("set5:", set5)

set5: {0, 2, 4, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 20, 25, 28, 35, 37, 40, 49, 50, 51, 53, 54, 55, 56, 61, 62, 63, 65, 66, 68, 69, 71, 75, 77, 78, 81, 83, 85, 86, 87, 92, 96}

#### What is the relationship among the following values:

* len(set1)
* len(set2)
* len(set3)
* len(set4)
* len(set5)

Use a math formular to represent that relationship. Test your formular with Python code.

In [10]:
# Math formulas (relationships)
print("len(set1) == len(set3) + len(set5):", len(set1) == len(set3) + len(set5))
print("len(set2) == len(set4) + len(set5):", len(set2) == len(set4) + len(set5))

len(set1) == len(set3) + len(set5): True
len(set2) == len(set4) + len(set5): True

#### Create an empty set called `set6`.

In [11]:
set6 = set()

#### Add `set3` and `set5` to `set6` using the Python Set `update` method.

In [12]:
set6.update(set3)
set6.update(set5)

#### Check if `set1` and `set6` are equal.

In [13]:
print("set1 equals set6?", set1 == set6)

set1 equals set6? True

#### Check if `set1` contains `set2` using the Python Set `issubset` method. Then check if `set1` contains `set3`.*

In [14]:
print("Is set2 a subset of set1?", set2.issubset(set1))
print("Is set3 a subset of set1?", set3.issubset(set1))

Is set2 a subset of set1? False
Is set3 a subset of set1? True

#### Using the Python Set `union` method, aggregate `set3`, `set4`, and `set5`. Then aggregate `set1` and `set2`.

#### Check if the aggregated values are equal.

In [15]:
union_345 = set3.union(set4, set5)
union_12 = set1.union(set2)

print("Are union(set3, set4, set5) and union(set1, set2) equal?", union_345 == union_12)

Are union(set3, set4, set5) and union(set1, set2) equal? True

#### Using the `pop` method, remove the first element from `set1`.

In [16]:
removed_item = set1.pop()
print("Removed item:", removed_item)

Removed item: 0

#### Remove every element in the following list from `set1` if they are present in the set. Print the remaining elements.

```
list_to_remove = [1, 9, 11, 19, 21, 29, 31, 39, 41, 49, 51, 59, 61, 69, 71, 79, 81, 89, 91, 99]
```

In [17]:
list_to_remove = [1, 9, 11, 19, 21, 29, 31, 39, 41, 49, 51, 59, 61, 69, 71, 79, 81, 89, 91, 99]

for item in list_to_remove:
    set1.discard(item)  # discard() avoids errors if item isn't in the set

print("Remaining elements in set1:", set1)

Remaining elements in set1: {2, 4, 8, 10, 12, 13, 14, 15, 16, 17, 18, 20, 22, 23, 24, 25, 26, 27, 28, 30, 32, 33, 34, 35, 36, 37, 40, 43, 44, 45, 46, 50, 53, 54, 55, 56, 57, 62, 63, 65, 66, 67, 68, 73, 74, 75, 76, 77, 78, 80, 82, 83, 84, 85, 86, 87, 88, 90, 92, 93, 96, 97, 100}